### ISSUE TITLE
feature: Add commentstring

### ISSUE THREAD

**Issue by mike-lloyd03** [tree-sitter-grammars/tree-sitter-arduino#29]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

When using nvim 0.10's native comment feature with Arduino files, I get an error:

```
Option 'commentstring' is empty.
```

I believe that is because the treesitter grammar for Arduino does not support comment strings. If I change the filetype to `c` or `c++`, the comment function works as expected.

### Describe the solution you'd like

Please add support for comment strings.

### Describe alternatives you've considered

Using an alternative commenting library in which I can override the language type.

This seems like something that should be supported by the grammar however.

**Comment by ObserverOfTime** [comment]
This is not a Vim plugin. The commentstring should be added to Vim or your own config.
